### ISSUE TITLE
Export types

### ISSUE THREAD

**Issue by www-chique** [chanced/filedrop-svelte#13]
Many thanks for this great module!

However, I came across some type issues.
If I use 
```declare type FileDropEvent = import("filedrop-svelte/lib/event").FileDropEvent;```
it doesn't work because "filedrop-svelte/lib/event" doesn't exist as it's not exported.

**Comment by chanced** [comment]
Hmm, it should be exported. I'll look into this later today.

Notes for myself:

https://github.com/chanced/filedrop-svelte/blob/c79817c21265e4cb09cd2a7564f5c47ef3723e0f/src/lib/index.ts#L4

https://github.com/chanced/filedrop-svelte/blob/c79817c21265e4cb09cd2a7564f5c47ef3723e0f/src/lib/event.ts#L5

**Comment by chanced** [comment]
Ah, the import location of the types changed at some point, somehow.

Use this instead:
```ts
declare type FileDropEvent = import('filedrop-svelte/event').FileDropEvent;
declare type FileDropSelectEvent = import('filedrop-svelte/event').FileDropSelectEvent;
declare type FileDropDragEvent = import('filedrop-svelte/event').FileDropDragEvent;
```
note to self: update the README

**Comment by www-chique** [comment]
It works now. Many thanks.
