### ISSUE TITLE
Error while dragging a file

### ISSUE THREAD

**Issue by PlkMarudny** [chanced/filedrop-svelte#15]
When I drag a file on the instrumented node, the following errors are thrown in console:

![image](https://user-images.githubusercontent.com/4361591/197940586-aa9ee1bc-af50-476a-8645-d6f23bb67cf6.png)

**Comment by chanced** [comment]
Do you happen to have a repro?

There may have been an upgrade to either svelte or kit which is breaking it. The REPL doesn't seem to be loading at all right now.

**Comment by chanced** [comment]
Nevermind, that was due to the fileSize dependency.

Please provide either a repro or at least your code.

**Comment by PlkMarudny** [comment]
Here is the REPL
<https://svelte.dev/repl/d555f696323c4b6e8a50e6f4d1f91ece?version=3.52.0>.
However, after updating Svelte to the REPLversion, i.e 3.52.0, the error is
gone. Thanks for the prompt reply.

Tomasz Plonka
