### ISSUE TITLE
Component Height is Hardcoded

### ISSUE THREAD

**Issue by N0tExisting** [chanced/filedrop-svelte#2]
Currently the component height is hardcoded at `200px` which is anoying as it is way to high for my purposes and might be to small for other people.

I've made a PR (#3)

**Comment by chanced** [comment]
Ah, the idea was that the default styles would only be applied if `class` were not provided. However, the assignment of the class isn't there and I need to add a slot.

I didn't realize that svelte doesn't recognize classes assigned to components. I'll switch it over to a `slot`. The default styles on the component were just meant to be a standin.

In the meantime, use the action.

```html
<div use:filedrop={options} on:filedrop={(e) => {files = e.detail.files}}></div>

**Comment by chanced** [comment]
Switching it to a `label` is causing an issue with the action, which erroneously assumes the container is a div or some other element. As a label, the click event is being sent to the input.

**Comment by chanced** [comment]
Thank you for the pr. Your changes have been published.
