### ISSUE TITLE
Incorrect error code thrown with FileSizeLimitExceededError

### ISSUE THREAD

**Issue by Antosik** [chanced/filedrop-svelte#7]
Hi!

I found that `FileSizeLimitExceededError` exception contains incorrect `ErrorCode` - `FileSizeMinimumNotMet` instead of `FileSizeMaximumExceeded`

Please, check it out: https://github.com/chanced/filedrop-svelte/blob/bae3e5f25dbd2cee2dcbd6d8b35e35bfba0c0db7/src/lib/errors.ts#L56-L64

**Comment by chanced** [comment]
sorry about that! this was resolved and pushed as version`0.1.2`
